version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: physic_user
      POSTGRES_PASSWORD: physic_pass
      POSTGRES_DB: physic_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - mongo
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DATABASE_URL=postgresql://physic_user:physic_pass@postgres:5432/physic_db

volumes:
  pgdata:
  mongodata:
