name: CI - Build & Publish Backend Image

# run on pushes to main and on PRs targeting main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# need package write permission so GITHUB_TOKEN can push to GHCR
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for cross-platform builds; optional)
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/physicalc-backend:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/physicalc-backend:latest

      - name: Verify image was pushed
        run: |
          echo "Image tags pushed:"
          echo "ghcr.io/${{ github.repository_owner }}/physicalc-backend:${{ github.sha }}"
          echo "ghcr.io/${{ github.repository_owner }}/physicalc-backend:latest"

